services:
  - type: web
    name: telnyx-telegram-sms
    runtime: python
    buildCommand: ""
    startCommand: "gunicorn app:app"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
